[package]
authors = ["Jake Goulding <jake.goulding@integer32.com>"]
name = "influxdb"
version = "0.1.0"

[dependencies]

[dev-dependencies]
hyper = "0.10.4"
reqwest = "0.4.0"
serde = "0.9.5"
serde_derive = "0.9.5"
serde_json = "0.9.4"
